In [41]:
import numpy as np
from numpy import zeros
from numpy import diag

outfile = 'data.npy'

class linear_eqation_class:
    def __init__(self, A):
        self.A = A
    
    
    def do_svd_decompostion(self):
        U, sigma, VT = np.linalg.svd(self.A, full_matrices=False)

        # reciprocals of sigma
        d = 1.0 / sigma
        # create m x n D matrix
        D = zeros(self.A.shape)
        #print(D)
        # populate D with n x n diagonal matrix
        D[:self.A.shape[1], :self.A.shape[1]] = diag(d)
        #print(D)
        
        # calculate pseudoinverse
        B = VT.T.dot(D.T).dot(U.T)
        #print(B)
        np.save(outfile, B)
    
    def do_least_sqaure(self,matrix_b):
        pseudoinverse_B = np.load(outfile)
        x = pseudoinverse_B * matrix_b 
        print('\nLeast-squares solution x:')
        print(x)

        # Error of solution ||A*x-b||**2
        eps = np.linalg.norm(matrix_b-self.A*x,ord=2)**2
        print('\nNorm value: ||b-A*x||**2 =', eps)

In [42]:
# Create a array
a_array = np.array([[1, 2], [2, 2]])
b_array = np.array([-1, 2])



In [43]:
linear_eqation_class_obj = linear_eqation_class(a_array)
linear_eqation_class_obj.do_svd_decompostion()
linear_eqation_class_obj.do_least_sqaure(b_array)


Least-squares solution x:
[[ 1.  2.]
 [-1. -1.]]

Norm value: ||b-A*x||**2 = 23.46585609973067


In [44]:
a_array = np.array([[1,0,-1,2],[1,1,1,-1],[0,-1,-2,3],[5,2,-1,4]])
b_array = np.array([-1, 2, -3, 1])

In [45]:
linear_eqation_class_obj = linear_eqation_class(a_array)
linear_eqation_class_obj.do_svd_decompostion()
linear_eqation_class_obj.do_least_sqaure(b_array)


Least-squares solution x:
[[-1.20392298e+15  2.24537868e+15 -5.76133239e+14 -4.65322464e+14]
 [ 8.49632626e+14  1.39878404e+15 -2.27846479e+15  3.00481211e+13]
 [ 1.91250369e+15 -9.53370413e+15  6.28532929e+15  1.33587115e+15]
 [ 1.55821333e+15 -5.88954140e+15  3.43073127e+15  9.00596807e+14]]

Norm value: ||b-A*x||**2 = 3.0729036423169622e+32
